# Generated by Django 3.2.12 on 2022-04-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='code',
            new_name='Code',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='Name',
        ),
    ]
