# Generated by Django 3.2.12 on 2022-04-24 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 4, 24)),
        ),
    ]
