# Generated by Django 3.2.12 on 2022-04-24 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_info_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
