# Generated by Django 3.2.12 on 2022-04-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_info_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='Affected',
            new_name='Confirmed',
        ),
    ]
